spring:
  servlet:
    multipart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: vamsi
#logging:
  #level:
    #org: debug

#logging:
  #level:
    #org:
    #springframework: ERROR
    #logging.level.root=debug


  #spring.datasource.url=jdbc:mysql://localhost:3306/employeedb
  #spring.datasource.username=root
  #spring.datasource.password=vamsi
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
